SQLALCHEMY_DATABASE_URI = 'sqlite:///pet_Test.db'
SECRET_KEY = "test"

AWS_ACCESS_KEY = "AKIAVE2UBMDZIFEAEC7G"
AWS_SECRET_ACCESS_KEY = "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"
AWS_S3_BUCKET_REGION = "ap-northeast-1"
AWS_S3_BUCKET_NAME = "cosmosaurtest"