"""empty message

Revision ID: 1439f117ff9f
Revises: 57d4bbdd15ae
Create Date: 2023-02-18 01:11:14.119805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1439f117ff9f'
down_revision = '57d4bbdd15ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routine', schema=None) as batch_op:
        batch_op.alter_column('routine_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('weekday',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routine', schema=None) as batch_op:
        batch_op.alter_column('weekday',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('routine_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
